In [2]:
import numpy as np


[1 2 3]


In [9]:
#question 1: reversing vector
import numpy as np
x=int(input('enter magnitude of vector in x direction'))
y=int(input('enter magnitude of vector in y direction'))
z=int(input('enter magnitude of vector in z direction'))
a=np.array([x,y,z])
b=a[::-1]      #using slicing method
print('given vector:',a[0],'i +',a[1],'j +',a[2],'k')
print('reversed vector:',b[0],'i +',b[1],'j +',b[2],'k')


enter magnitude of vector in x direction1
enter magnitude of vector in y direction5
enter magnitude of vector in z direction8
given vector: 1 i + 5 j + 8 k
reversed vector: 8 i + 5 j + 1 k


In [23]:
#question 2:
#c=np.array([[0,1,2],[3,4,5],[6,7,8]])
import numpy as np
c=np.arange(0,9,1).reshape(3,3)
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [39]:
#question 3:
import numpy as np
print('enter order of matrix')
n=int(input())
m=int(input())
d=np.ones((n,m))
d[1:-1,1:-1]=0
print(d)

enter orde of matrix 

3
4
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [46]:
#question 4:
import numpy as np
p=np.random.random((5,3))
print('matrix 1:\n',p)
q=np.random.random((3,2))
print('matrix 2:\n',q)
print('multiplied matrix:\n',np.dot(p,q))

matrix 1:
 [[0.80256099 0.96522229 0.30577949]
 [0.92349356 0.73079864 0.19712646]
 [0.88190736 0.28428799 0.90067328]
 [0.54258536 0.85140536 0.96829658]
 [0.30576863 0.53296916 0.48753968]]
matrix 2:
 [[0.17121377 0.33042712]
 [0.81101116 0.36916461]
 [0.26262938 0.08209652]]
multiplied matrix:
 [[1.00052222 0.64661725]
 [0.80257186 0.5911157 ]
 [0.61809869 0.47029731]
 [1.03770046 0.57308742]
 [0.61263798 0.33781291]]


In [47]:
#question 5:
import numpy as np

In [83]:
#question 6:
import numpy as np
w=np.random.random((2,2))
z=np.random.random((2,2))
print('matrix 1:\n',w)
print('matrix 2:\n',z)
print('matrix 1 and 2 are')
x=w==z
if np.all(x):
    print('equal')
else:
    print('not equal')

matrix 1:
 [[0.15219055 0.86817765]
 [0.08909354 0.65281982]]
matrix 2:
 [[0.28861497 0.25978806]
 [0.14357988 0.25618791]]
matrix 1 and 2 are
not equal


In [94]:
#question 7:
import numpy as np
arr=np.random.random((10))
print(arr)
value=float(input('enter value '))
print('nearest value is :',arr[(np.abs(arr-value)).argmin()])


[0.73496506 0.91352026 0.34691687 0.19970042 0.0304056  0.48990271
 0.97642958 0.81576716 0.79028296 0.74629474]
enter value 0.7
nearest value is : 0.7349650579780866


In [96]:
#question 8:
import numpy as np
arr=np.random.random((10))
print(arr)
print('largest value is :',arr[arr.argmax()])

[0.34558132 0.53818409 0.37678619 0.16772011 0.93827128 0.85780433
 0.52190143 0.76188945 0.24224462 0.17235382]
largest value is : 0.9382712806125896


In [ ]:
#question 9:
import numpy as np
arr=np.random.random((10))
print(arr)
value=float(input('enter value '))
print('nearest value is :',arr[(np.abs(arr-value)).argmin()])

In [3]:
#question 10:
import numpy as np
arr=np.random.random((15))
print(arr)
arr[arr.argmin()]=-1
print('after replacing min value with -1 :\n',arr)

[0.11457102 0.70875698 0.26263538 0.08096529 0.64488877 0.08456574
 0.89275174 0.24215601 0.14856026 0.85524735 0.88767089 0.14361793
 0.22829724 0.09641967 0.29506654]
after replacing min value with -1 :
 [ 0.11457102  0.70875698  0.26263538 -1.          0.64488877  0.08456574
  0.89275174  0.24215601  0.14856026  0.85524735  0.88767089  0.14361793
  0.22829724  0.09641967  0.29506654]


In [11]:
#question 11:
import math
import numpy as np
points=np.random.random((100,2))
#print(points)
for i in points-1:
    print(math.sqrt(i[0]-(i+1)[0]))

[-0.6303703  -0.29382747]
[-0.84111118 -0.04477595]
[-0.50786901 -0.69500682]
[-0.94560466 -0.87193736]
[-0.06896737 -0.6975566 ]
[-0.85049611 -0.10752524]
[-0.80964534 -0.44611274]
[-0.18424922 -0.24977688]
[-0.94965056 -0.26889945]
[-0.2135803  -0.47877333]
[-0.17976604 -0.41672891]
[-0.9669915 -0.5576709]
[-0.28112421 -0.69821676]
[-0.6901545  -0.11740332]
[-0.50603407 -0.15907293]
[-0.5571364 -0.7617407]
[-0.04016442 -0.04445364]
[-0.66234777 -0.9308627 ]
[-0.7043242  -0.85590262]
[-0.83877546 -0.23217118]
[-0.03919045 -0.49011791]
[-0.34765987 -0.68198065]
[-0.30880146 -0.67470605]
[-0.55266223 -0.0022652 ]
[-0.13973789 -0.99022845]
[-0.63788938 -0.63045921]
[-0.7239245  -0.12702785]
[-0.95073165 -0.44915236]
[-0.79404272 -0.40427099]
[-0.88572386 -0.75589713]
[-0.12055265 -0.31298507]
[-0.99966752 -0.42329662]
[-0.97190419 -0.67238514]
[-0.7064018 -0.2494991]
[-0.61069821 -0.96097944]
[-0.64651405 -0.22716104]
[-0.8658398 -0.7590142]
[-0.50374041 -0.31344794]
[-0.33150337 -0.4697

In [10]:
#question 12
import numpy as np
print('enter order of matrix')
n=int(input())
m=int(input())
arr=np.random.random((n,m))
print('initial matrix :\n',arr)
#arr=[[3,4,5,3,8,3],[2,9,3,7,4,9],[4,7,1,9,3,7]]
x=int(input('enter column index to be sorted '))
arr = arr[arr[:,x].argsort()]
print('matrix after sorting :\n',arr)

enter order of matrix
3
4
initial matrix :
 [[0.75702798 0.12983095 0.48709416 0.56173399]
 [0.14626823 0.2444499  0.49710947 0.61850307]
 [0.37611087 0.14252874 0.45646854 0.84794884]]
enter column to be sorted 3
matrix after sorting :
 [[0.75702798 0.12983095 0.48709416 0.56173399]
 [0.14626823 0.2444499  0.49710947 0.61850307]
 [0.37611087 0.14252874 0.45646854 0.84794884]]


In [15]:
#question 13
import numpy as np
arr=np.random.random((2,3,3,2))
print(arr)
print('sum of last 2 axis is: ',np.sum(arr[axis=(-1,-2)]))

SyntaxError: invalid syntax (<ipython-input-15-ddbf209f61d9>, line 5)

In [17]:
#question 14:
import numpy as np
a = np.array([1,2,3,1,2,1,1,1,3,2,2,1])
counts = np.bincount(a)
print(np.argmax(counts))


1
