In [1]:
import numpy as np

In [37]:
#reverse array
x=np.arange(1,10)
print(x)
y=x[::-1]
print(y)

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]


In [38]:
#3*3 matrix 0-8

In [39]:
a = np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [54]:
#2d array with 1 on the border and 0 inside
n = input()
a = np.ones((int(n),int(n)),dtype=np.int64)
a[1:-1,1:-1]=0
print(a)

5
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [60]:
#Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
a = np.random.random((5,3))
print(a)
print('')
b = np.random.random((3,2))
print(b)
print('')
c = np.dot(a,b)
print(c)

[[0.96511458 0.4659734  0.28349425]
 [0.59851573 0.68608783 0.16558568]
 [0.75381641 0.09300748 0.3896926 ]
 [0.23215354 0.16140283 0.45846296]
 [0.27010203 0.53995674 0.40073385]]

[[0.39036763 0.80366769]
 [0.45233223 0.63749524]
 [0.98729332 0.85304157]]

[[0.86741627 1.31451961]
 [0.70746245 1.05963695]
 [0.72107671 0.99753371]
 [0.61627035 0.6805558 ]
 [0.74532079 0.90313476]]


In [74]:
#Extract the integer part of a random array using 5 differentmethods
a = np.random.uniform(2,3,4)
print(a)
print('')
print (a - a%1)
print('')
print (np.floor(a))
print('')
print (np.ceil(a)-1)
print('')
print (a.astype(int))
print('')
print (np.trunc(a))

[2.65468427 2.97791305 2.8249959  2.60705813]

[2. 2. 2. 2.]

[2. 2. 2. 2.]

[2. 2. 2. 2.]

[2 2 2 2]

[2. 2. 2. 2.]


In [87]:
#Python program to check two random arrays are equal or not.
x = np.random.randint(0,2,6)
print(x)
print('')
y = np.random.randint(0,2,6)
print(y)
print('')
arr_equal = np.allclose(x, y)
print(arr_equal)

[1 0 1 0 1 0]

[1 0 1 0 1 0]

True


In [89]:
#Python program to find the nearest value from a given value in anarray.
import numpy as np
x = np.random.uniform(1, 12, 5)
key = int(input())
n = x.flat[np.abs(x - key).argmin()]
print(n)

5
4.496533769285221


In [92]:
#largest value of an array
x = np.arange(11)
print(x)
print('')
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

[ 0  1  2  3  4  5  6  7  8  9 10]

[10]


In [94]:
#the closest value (to a given scalar) in an array
x = np.arange(10)
print(x)
a = np.random.uniform(0,10)
print(a)
index = (np.abs(x-a)).argmin()
print(x[index])

[0 1 2 3 4 5 6 7 8 9]
3.935146415755968
4


In [96]:
# the most frequent value in an array
a = np.random.randint(0,20,10)
print(a)
print('')
print(np.bincount(a).argmax())

[13  7  7  7  2  3 16 16  2 11]

7


In [100]:
# four dimensions array, how to get sum over thelast two axis at once
a = np.random.randint(0,50,(10,20,10,20))
sum = a.sum(axis=(-2,-1))
print(sum)
print('')
sum = a.reshape(a.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[4837 4654 4527 5150 4960 5026 4447 4651 4835 4907 4848 4856 4933 4742
  4886 4847 4845 4952 5085 4821]
 [4739 4910 4643 5248 4839 4791 4754 4902 4790 5161 5182 4652 4910 5225
  5096 5256 5052 4763 4474 4903]
 [4756 5268 5074 5022 4860 4810 4947 4740 4860 4667 4837 4847 4882 5217
  4950 4918 4586 4985 4987 5037]
 [4832 4398 4644 5131 4343 5128 4798 5101 4982 4929 4883 4884 5009 4831
  4738 5173 4480 4715 4710 4939]
 [4776 5096 4511 4956 4764 4885 5051 4707 4984 4785 5141 4716 4806 4625
  5146 4707 5075 4791 4888 4693]
 [4924 4940 4834 4897 5253 5086 5631 4607 4874 4992 4964 4578 4680 4899
  4975 4808 5031 5091 4300 4586]
 [5153 4655 4804 4959 4682 4994 4938 4893 5131 5047 4902 5007 5059 5071
  5279 5197 4997 5251 4967 4817]
 [5330 4845 5090 4887 4775 4853 5207 4817 5328 5017 4690 4893 4929 5152
  5324 4701 5068 5073 5079 4684]
 [4615 5076 4792 5073 5064 4784 5052 5091 5070 5196 5030 4962 4718 4862
  4859 4588 4997 4683 5193 5164]
 [4665 4643 5250 5106 4930 4802 4806 4804 4919 5146 496

In [101]:
#sort an array by the nth column
a = np.random.randint(0,50,(10,10))
print(a)
print(a[a[:,1].argsort()])

[[31  1 29 20 24 18 16 41 46 44]
 [ 6 46 11 37 43 41 16  3  5 46]
 [42 44 47 36 10 31  5 14 38 19]
 [49 13 17 12 27  2  9  9  1  6]
 [14  5 36 12 21 37 31 16  9 42]
 [33  7 18  6 36 10  0 18 22 18]
 [44 23 44 27 31 48  7 28 24 29]
 [ 0 13 14  1 13 32 12 40 18 45]
 [47  2 44 20 31 47 28 47  0 35]
 [ 8 26 37 41 41 46 22 25 11 13]]
[[31  1 29 20 24 18 16 41 46 44]
 [47  2 44 20 31 47 28 47  0 35]
 [14  5 36 12 21 37 31 16  9 42]
 [33  7 18  6 36 10  0 18 22 18]
 [49 13 17 12 27  2  9  9  1  6]
 [ 0 13 14  1 13 32 12 40 18 45]
 [44 23 44 27 31 48  7 28 24 29]
 [ 8 26 37 41 41 46 22 25 11 13]
 [42 44 47 36 10 31  5 14 38 19]
 [ 6 46 11 37 43 41 16  3  5 46]]


In [103]:
# random vector with shape (100,2) representingcoordinates, find point by point distances
a = np.random.random((10,2))
x,y = np.atleast_2d(a[:,0], a[:,1])
b = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(b)
print('')
print('')
import scipy
import scipy.spatial
a = np.random.random((10,2))
b = scipy.spatial.distance.cdist(a,a)
print(b)


[[0.         0.38110364 0.95840035 0.69394174 0.35009556 0.20754897
  0.83731882 0.70426155 0.83907353 0.49631457]
 [0.38110364 0.         0.64539376 0.38472776 0.21976874 0.44581291
  0.52316695 0.36386231 0.49889005 0.18040939]
 [0.95840035 0.64539376 0.         0.26678752 0.85376307 0.89487595
  0.12310697 0.28527163 0.16699691 0.70985713]
 [0.69394174 0.38472776 0.26678752 0.         0.59978562 0.64781825
  0.14405463 0.08084742 0.15966144 0.47789886]
 [0.35009556 0.21976874 0.85376307 0.59978562 0.         0.50594483
  0.73356986 0.5686499  0.69857211 0.18794415]
 [0.20754897 0.44581291 0.89487595 0.64781825 0.50594483 0.
  0.78206472 0.68147806 0.8055732  0.60587071]
 [0.83731882 0.52316695 0.12310697 0.14405463 0.73356986 0.78206472
  0.         0.16772386 0.08844455 0.59608   ]
 [0.70426155 0.36386231 0.28527163 0.08084742 0.5686499  0.68147806
  0.16772386 0.         0.13646245 0.42848411]
 [0.83907353 0.49889005 0.16699691 0.15966144 0.69857211 0.8055732
  0.08844455 0.136462

In [105]:
#Python program to create random vector of size 15 and replacethe maximum value by -1
x=np.random.random(15)
print (x)
print('')
x[x.argmax()]=-1
print (x)

[0.47717369 0.47959102 0.48905694 0.17168448 0.704967   0.83612305
 0.87329476 0.10810613 0.82828771 0.87013079 0.73308426 0.20178965
 0.72051163 0.27922553 0.56274012]

[ 0.47717369  0.47959102  0.48905694  0.17168448  0.704967    0.83612305
 -1.          0.10810613  0.82828771  0.87013079  0.73308426  0.20178965
  0.72051163  0.27922553  0.56274012]
