In [1]:
import numpy as np
#Question 1
a=np.array([1,2,3,4,5,6,7,8])
reverse_a = np.fliplr([a])
print(reverse_a)


[[8 7 6 5 4 3 2 1]]


In [2]:
#Question 2
matrix = np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [3]:
#Question 3
b=np.zeros((5,5))
c=np.ones((5))
b[:1]=c
b[4:]=c
b[:,0]=c
b[:,4]=c
print(b)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [4]:
#Question 4
c=np.array([[2,3,4],[3,4,5],[5,6,7],[7 ,8 ,9],[10,11,12]])
d=np.array([[1,2],[2,3],[3,4]])
e=c@d   #Matrix multiplication
print(e)

[[ 20  29]
 [ 26  38]
 [ 38  56]
 [ 50  74]
 [ 68 101]]


In [5]:
#Question 5
Z = np.random.uniform(1,10,5)
print(Z)

print (np.rint(Z))  #1
print (Z - Z%1)     #2
print (np.floor(Z))  #3
print (np.ceil(Z)-1)  #4
print (np.trunc(Z))   #5

[3.47007173 4.45936796 3.14620281 3.607395   1.05986905]
[3. 4. 3. 4. 1.]
[3. 4. 3. 3. 1.]
[3. 4. 3. 3. 1.]
[3. 4. 3. 3. 1.]
[3. 4. 3. 3. 1.]


In [6]:
#Question 6

A=np.random.normal(size=5)
B=np.random.normal(size=5)
if np.array_equal(A,B):
  print('EQUAL')
else:
 print('NOT EQUAL')

NOT EQUAL


In [7]:
#Question 7
def nearestValue(array,value):
    ind=(np.abs(array-value)).argmin()
    return array[ind]
q = np.random.normal(1,15,10)
value= 5
print(nearestValue(q,value))

8.638328281639776


In [8]:
#Question 8
a=np.array([2,13,4,1,6,0,9,5])


b=-np.sort(-a)
n=4    # n largest numbers

print(b[:n])

[13  9  6  5]


In [9]:
#Question 9
def nearestValue(array,value):
    ind=(np.abs(array-value)).argmin()
    return array[ind]
q = np.random.normal(1,15,10)
value= 8
print(nearestValue(q,value))

8.793327845137693


In [10]:
#Question 10
A=np.random.normal(size=15)
A=-np.sort(-A)  #Sorted in Descending order
A[0]=-1
print(A)


[-1.          1.73669513  1.42459271  1.15696612  0.6260949   0.54070942
  0.50452188  0.3385939   0.05646326 -0.64475989 -0.83142749 -1.16057233
 -1.22671335 -1.31703436 -1.40777198]


In [11]:
#Question 11
A=np.random.normal(1,100,20).reshape(10,2)
B=A[:,:1]
C=A[:,1:2]
D=np.sqrt((B-B.T)**2 + (C-C.T)**2)
print(D)

[[  0.          50.58525355  39.96354349  75.44653909 258.5066335
  298.37257964 267.37659407  45.33349837 113.15853537 315.4894385 ]
 [ 50.58525355   0.          68.0016789   60.94029576 207.96865435
  254.05486775 256.68303107  34.63767058  64.47269343 313.49643373]
 [ 39.96354349  68.0016789    0.         111.89704385 267.5997428
  287.34933356 231.5101998   39.51624979 116.58735733 355.4527458 ]
 [ 75.44653909  60.94029576 111.89704385   0.         219.39023092
  294.67770761 317.61001098  91.61433099 106.60827264 252.66278716]
 [258.5066335  207.96865435 267.5997428  219.39023092   0.
  142.91517573 318.96937101 228.15095874 151.21354517 374.98384486]
 [298.37257964 254.05486775 287.34933356 294.67770761 142.91517573
    0.         223.10623779 254.976411   191.01236236 501.48938378]
 [267.37659407 256.68303107 231.5101998  317.61001098 318.96937101
  223.10623779   0.         229.49378887 233.74562628 569.7679806 ]
 [ 45.33349837  34.63767058  39.51624979  91.61433099 228.1509587

In [12]:
#Question 12    
S=np.random.normal(1,10,25).reshape(5,5)
print(S)
R=S[S[:1].argsort()]
print(R)


[[ -4.86221084   5.48616844  -8.87011275   3.47898136  10.7956396 ]
 [ -4.18483904  -5.19571808   6.12694195  -5.60638799   0.58859241]
 [  1.23047359  -9.29385247   7.46177847  14.72603519 -10.0411641 ]
 [ -1.24549999  -7.88843864  -2.99997992   3.25925071   2.67205928]
 [ 22.35395018   7.77767087  21.92078046   5.17350076   2.20362176]]
[[[  1.23047359  -9.29385247   7.46177847  14.72603519 -10.0411641 ]
  [ -4.86221084   5.48616844  -8.87011275   3.47898136  10.7956396 ]
  [ -1.24549999  -7.88843864  -2.99997992   3.25925071   2.67205928]
  [ -4.18483904  -5.19571808   6.12694195  -5.60638799   0.58859241]
  [ 22.35395018   7.77767087  21.92078046   5.17350076   2.20362176]]]


In [13]:
#Question 13
A=np.random.uniform(1,10,16).reshape(2,2,2,2)
print(A)
print(np.sum(A,axis=(2,3)))

[[[[5.58213366 6.05056069]
   [8.92817552 3.51663382]]

  [[2.79074757 7.7009718 ]
   [8.92166503 1.87809036]]]


 [[[9.15245916 2.22424336]
   [8.3232333  2.24291664]]

  [[4.37841194 7.4211781 ]
   [8.90881605 4.04699449]]]]
[[24.07750369 21.29147476]
 [21.94285246 24.75540059]]


In [14]:
#Question 14
E = np.random.randint(0,10,50)
print(E)
print(np.bincount(E).argmax())

[5 3 5 8 3 2 0 7 7 3 6 7 0 9 5 5 6 2 9 1 3 6 8 4 6 2 9 6 8 5 5 5 6 2 5 9 1
 7 8 1 5 7 0 4 3 1 2 6 8 1]
5
