In [1]:
import numpy as np

In [2]:
a = np.random.random((5,5))
print(a)

[[0.92599973 0.25006254 0.2947978  0.18069982 0.87263072]
 [0.88267571 0.73237728 0.8032546  0.56871642 0.34713092]
 [0.13052877 0.74619817 0.22751923 0.48809188 0.14687185]
 [0.96245456 0.08373452 0.84644944 0.28612437 0.6546962 ]
 [0.29069959 0.68455553 0.49998185 0.96651456 0.0124093 ]]


In [3]:
b = np.sort(a, axis=0)

In [4]:
print(b)

[[0.13052877 0.08373452 0.22751923 0.18069982 0.0124093 ]
 [0.29069959 0.25006254 0.2947978  0.28612437 0.14687185]
 [0.88267571 0.68455553 0.49998185 0.48809188 0.34713092]
 [0.92599973 0.73237728 0.8032546  0.56871642 0.6546962 ]
 [0.96245456 0.74619817 0.84644944 0.96651456 0.87263072]]


In [5]:
n = 2

In [6]:
i = 0

In [7]:
while (i<5):
    print(b[i][n])
    i = i + 1

0.22751922672066294
0.29479779600091827
0.49998185192161204
0.8032546023809215
0.8464494350344361
