In [1]:
import numpy as np

In [2]:
A = np.random.randint(0,10,(3,4,3,4))

sum = A.sum(axis=(-2,-1))
print(sum)

sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[54 56 55 50]
 [51 65 57 61]
 [70 69 63 51]]
[[54 56 55 50]
 [51 65 57 61]
 [70 69 63 51]]
