In [1]:
import numpy as np

In [2]:
a = np.random.random((5,3))
print(a)

[[0.77733147 0.1879185  0.16393933]
 [0.33163568 0.38992644 0.5305067 ]
 [0.71233989 0.96828031 0.51161643]
 [0.4076207  0.89119755 0.7817306 ]
 [0.47395589 0.62667244 0.20115892]]


In [3]:
b = np.random.random((3,2))
print(b)

[[0.75122959 0.35046025]
 [0.34252476 0.87491531]
 [0.84833939 0.46792428]]


In [8]:
np.matmul(a, b)

array([[0.78739733, 0.51354774],
       [0.83274373, 0.7056147 ],
       [1.30081515, 1.33620782],
       [1.27464682, 1.28836796],
       [0.74135155, 0.80851515]])