In [1]:
import numpy as np

In [5]:
a = np.random.uniform(0,10,10)
print(a)

print (np.trunc(a))
print (a - a%1)
print (np.floor(a))
print (np.ceil(a)-1)
print (a.astype(int))



[4.57496707 1.90052363 9.27726025 4.39302626 8.02327108 5.66708389
 4.58847269 6.52977139 7.23135322 8.76969048]
[4. 1. 9. 4. 8. 5. 4. 6. 7. 8.]
[4. 1. 9. 4. 8. 5. 4. 6. 7. 8.]
[4. 1. 9. 4. 8. 5. 4. 6. 7. 8.]
[4. 1. 9. 4. 8. 5. 4. 6. 7. 8.]
[4 1 9 4 8 5 4 6 7 8]
