In [15]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [28]:
import numpy as np
def Hypothesis(theta,X):
#    X=np.array([1,2,3])
 #   theta=np.array([[3],[2],[1]])
#Calculate the hypothesis function h(X1 , X2)
    
    H=X.dot(theta)
    
    return(H)


In [29]:
def Cost_Function(H,Y,X,theta,m):
    summation=0 
    Ht=np.transpose(H)
    for i in range(len(Y)):
        summation=summation+(H[i]-Y[i])**2
        
    #print(summation)
    J=(1/(2*m))*summation
    
    return(J)


In [85]:
def Cost_Function_Derivative(X,Y,theta,J,m,H):

    Xt=np.transpose(X)
    dJ=(1/m)*(Xt.dot(np.transpose(H-Y)))
    #print(dJ,':cost function derivative\n')
    return(dJ)

In [82]:
def Linear_Regression(X,Y,alpha,theta,num_iters):
    m = len(X)
    for x in range(num_iters):
        H=Hypothesis(theta,X)
        Ht=np.transpose(H)
        J=Cost_Function(H,Y,X,theta,m)
        
        dJ=Cost_Function_Derivative(X,Y,theta,J,m,Ht)
       
        
        new_theta = Gradient_Descent(X,Y,theta,m,alpha,dJ)
        theta = new_theta
        if x % 100 == 0:
            print(new_theta)
            print(theta,':theta ')
            print(Cost_Function(H,Y,X,theta,m),':cost  ')
    return new_theta

In [83]:
def Gradient_Descent(X,Y,t,m,alpha,dJ):
    for i in range(len(t)):
        t[i]=float(t[i]-alpha*dJ[i][0])
        
    return(t)

In [86]:
Y= [19, 20, 20.5, 21.5, 22, 23, 23, 25.5, 24]
X = [[1,1],[1,2],[1,3],[1,4],[1,5],[1,6],[1,7],[1,8],[1,9]]
theta=np.array([[2],[3],[4]],dtype=np.float64)

x=np.empty((len(Y),3))
  
for i in range(len(Y)):
    x[i][0]=1
    x[i][1]=X[i][0]
    x[i][2]=X[i][1]
print

Linear_Regression(x,Y,0.01,theta,2000)

[[1.97055556]
 [2.97055556]
 [3.63388889]]
[[1.97055556]
 [2.97055556]
 [3.63388889]] :theta 
[40.43055556] :cost  
[[4.13164765]
 [5.13164765]
 [2.18934778]]
[[4.13164765]
 [5.13164765]
 [2.18934778]] :theta 
[9.1657291] :cost  
[[5.65463306]
 [6.65463306]
 [1.7022396 ]]
[[5.65463306]
 [6.65463306]
 [1.7022396 ]] :theta 
[4.19425522] :cost  
[[6.67387148]
 [7.67387148]
 [1.3762487 ]]
[[6.67387148]
 [7.67387148]
 [1.3762487 ]] :theta 
[1.96763956] :cost  
[[7.35598372]
 [8.35598372]
 [1.15808347]]
[[7.35598372]
 [8.35598372]
 [1.15808347]] :theta 
[0.97038655] :cost  
[[7.81247857]
 [8.81247857]
 [1.0120792 ]]
[[7.81247857]
 [8.81247857]
 [1.0120792 ]] :theta 
[0.52373849] :cost  
[[8.11798189]
 [9.11798189]
 [0.91436771]]
[[8.11798189]
 [9.11798189]
 [0.91436771]] :theta 
[0.32369448] :cost  
[[8.32243607]
 [9.32243607]
 [0.84897555]]
[[8.32243607]
 [9.32243607]
 [0.84897555]] :theta 
[0.2340991] :cost  
[[8.4592644 ]
 [9.4592644 ]
 [0.80521269]]
[[8.4592644 ]
 [9.4592644 ]
 [0.805212

array([[8.73386752],
       [9.73386752],
       [0.71738425]])