In [52]:
from sklearn import datasets
import pandas as pd
def loaddata():
    iris=datasets.load_iris()
    data_x=iris.data
    data_y=iris.target
    
    """ df=pd.DataFrame(data_x)
    df.columns=iris.feature_names
    df['CLASS']=iris.target
    df.head()"""
    splitdata(data_x,data_y)
    
   
    
loaddata()


size of training data= 102
size of test data= 48
value of k= 4
[6.  2.7 5.1 1.6] : predicted value= 2    actual value= 1
[5.1 3.5 1.4 0.2] : predicted value= 0    actual value= 0
[7.7 3.  6.1 2.3] : predicted value= 2    actual value= 2
[5.8 2.7 4.1 1. ] : predicted value= 1    actual value= 1
[5.1 3.8 1.6 0.2] : predicted value= 0    actual value= 0
[4.8 3.4 1.6 0.2] : predicted value= 0    actual value= 0
[7.9 3.8 6.4 2. ] : predicted value= 2    actual value= 2
[5.2 4.1 1.5 0.1] : predicted value= 0    actual value= 0
[6.1 3.  4.9 1.8] : predicted value= 2    actual value= 2
[6.4 2.8 5.6 2.1] : predicted value= 2    actual value= 2
[6.3 2.7 4.9 1.8] : predicted value= 2    actual value= 2
[4.4 3.2 1.3 0.2] : predicted value= 0    actual value= 0
[4.8 3.  1.4 0.1] : predicted value= 0    actual value= 0
[6.9 3.1 5.4 2.1] : predicted value= 2    actual value= 2
[4.9 2.5 4.5 1.7] : predicted value= 1    actual value= 2
[5.4 3.4 1.7 0.2] : predicted value= 0    actual value= 0
[4.3 3.  

In [31]:
from sklearn.cross_validation import train_test_split
import random
import numpy as np
def splitdata(data_x,data_y):
    while 1:
        split=random.random()
        if split<0.33:
            break
    train_x,test_x,train_y,test_y=train_test_split(data_x,data_y,test_size=split)
    print('size of training data=',len(train_x))
    print('size of test data=',len(test_x))
    predictions(train_x,train_y,test_x,test_y)


In [47]:
from sklearn.neighbors import KNeighborsClassifier
def predictions(train_x,train_y,test_x,test_y):
    k=random.randrange(1,10)
    print('value of k=',k)
    knn=KNeighborsClassifier(k)
    knn.fit(train_x,train_y)
    predicted=knn.predict(test_x)
    for i in range(len(test_x)):
        print(test_x[i],': predicted value=',predicted[i],'   actual value=',test_y[i])
    e = 0
    for i in range(len(predicted)):
        if predicted[i]==test_y[i]:
            e+=1
    accuracy=(e/len(test_y))*100
    print('\nAccuracy:', accuracy)