In [1]:
import numpy as np

In [5]:
#1 reversing a vector
a=np.array([1,2,3])
print (a)
b=a[::-1]
print (b)

[1 2 3]
[3 2 1]


In [34]:
#2  3x3 matrix
b=np.arange(9).reshape(3,3)
print (b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [39]:
#3 2D array with 1 on border , 0 inisde
a=input("Enter array size")
c=np.ones((int(a),int(a)),dtype=np.int16)
c[1:-1,1:-1]=0
print (c)

Enter array size8
[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]


In [12]:
#4 matrix multiplication
d=np.array([[1,2,3],[2,3,4],[4,5,6],[5,6,7],[7,8,9]])
e=np.array([[1,2],[3,4],[5,6]])
print (np.dot(d,e))

[[ 22  28]
 [ 31  40]
 [ 49  64]
 [ 58  76]
 [ 76 100]]


In [42]:
#5 extracting the integer part of a matrix
Z = np.random.uniform(0,10,10)
print (Z)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))


[1.79150327 4.76961214 0.13186952 6.22461576 1.35134908 5.82826455
 4.50473779 9.14945455 1.38013266 0.97395993]
[1. 4. 0. 6. 1. 5. 4. 9. 1. 0.]
[1. 4. 0. 6. 1. 5. 4. 9. 1. 0.]
[1. 4. 0. 6. 1. 5. 4. 9. 1. 0.]
[1 4 0 6 1 5 4 9 1 0]
[1. 4. 0. 6. 1. 5. 4. 9. 1. 0.]


In [15]:
#6 check equality of 2 random arrays
a=np.random.random((2,2))
b=np.random.random((2,2))
if np.array_equal(a,b):
    print ("the arrays are equal")
else :
    print ("arrays are not equal")
  

arrays are not equal


In [52]:
#7 check nearest value
Z = np.random.uniform(0,1,10)
print (Z)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

[0.46330811 0.79094339 0.43741449 0.3933317  0.27044666 0.36286176
 0.77413619 0.89895954 0.34750933 0.97976812]
0.4633081060700275


In [57]:
#8 n largest values of array
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print(Z)

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[8985 8256 1958 ... 9536 4403 5483]
[9995 9996 9997 9998 9999]
[9996 9997 9998 9999 9995]


In [59]:
#9 closest value to given scalar
Z = np.arange(100)
print (Z)
v = np.random.uniform(0,100)
print (v)
index = (np.abs(Z-v)).argmin()
print(Z[index])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
82.25300899092824
82


In [58]:
#10 replace maximum by -1
a=np.random.random(15)
print (a)
a[a.argmax()]=-1
print (a)

[0.9820089  0.33225098 0.14088192 0.23972065 0.2097106  0.29493173
 0.55707467 0.03868857 0.33203945 0.54955241 0.64825722 0.18583143
 0.6216062  0.8791643  0.89081135]
[-1.          0.33225098  0.14088192  0.23972065  0.2097106   0.29493173
  0.55707467  0.03868857  0.33203945  0.54955241  0.64825722  0.18583143
  0.6216062   0.8791643   0.89081135]


In [49]:
#11 100 points and distances between them
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.167936   0.38003125 0.41591376 0.59780834 0.54202836
  0.12450123 0.62291814 0.35963342 0.71227215]
 [0.167936   0.         0.2358878  0.33885103 0.46955645 0.40772637
  0.14063486 0.50759261 0.52640069 0.56838764]
 [0.38003125 0.2358878  0.         0.1972011  0.23652083 0.17279927
  0.37596808 0.57193508 0.71144002 0.33400832]
 [0.41591376 0.33885103 0.1972011  0.         0.23477631 0.21171758
  0.46755818 0.76410561 0.67223085 0.37544949]
 [0.59780834 0.46955645 0.23652083 0.23477631 0.         0.06579374
  0.61019106 0.74683003 0.89542851 0.14164005]
 [0.54202836 0.40772637 0.17279927 0.21171758 0.06579374 0.
  0.54821139 0.686998   0.85119296 0.17520387]
 [0.12450123 0.14063486 0.37596808 0.46755818 0.61019106 0.54821139
  0.         0.50327119 0.45388469 0.70679762]
 [0.62291814 0.50759261 0.57193508 0.76410561 0.74683003 0.686998
  0.50327119 0.         0.94611245 0.75102873]
 [0.35963342 0.52640069 0.71144002 0.67223085 0.89542851 0.85119296
  0.45388469 0.9461124

In [25]:
# 12. sort nth column
a=np.random.random((3,4))
print (a)
a.sort(axis=0)
print (a)

[[0.32173992 0.0751588  0.15005538 0.39260972]
 [0.47704628 0.65623072 0.87661249 0.89650923]
 [0.34209015 0.16853852 0.23601517 0.58107085]]
[[0.32173992 0.0751588  0.15005538 0.39260972]
 [0.34209015 0.16853852 0.23601517 0.58107085]
 [0.47704628 0.65623072 0.87661249 0.89650923]]


In [50]:
#12 Sort by nth column
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[1 4 2]
 [7 2 6]
 [7 1 9]]
[[7 1 9]
 [7 2 6]
 [1 4 2]]


In [60]:
#13 4D array- sum over last two axis
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[77 46 41 54]
 [45 58 54 59]
 [49 33 60 46]]
[[77 46 41 54]
 [45 58 54 59]
 [49 33 60 46]]


In [55]:
#14 most frequent value in array
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[3 9 0 6 5 4 4 9 2 9 3 9 3 8 3 6 9 2 2 1 4 8 7 0 0 3 8 3 7 6 9 8 6 0 1 4 0
 6 7 8 5 8 1 0 4 3 8 5 9 4]
3
