In [28]:
#Reversing a Vector
import numpy as np
arr=np.array(['1','2','3','4'])
reversed_arr = arr[::-1]
print(arr)
print(reversed_arr)

['1' '2' '3' '4']
['4' '3' '2' '1']


In [7]:
#Create a 3x3 matrix with values ranging from 0 to 8
import numpy as np
a=np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
#Create a 2d array with 1 on the border and 0 inside
import numpy as np
a=np.ones((4,6))
a[1:-1,1:-1]=0
print(a)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [27]:
#Multiply a 5x3 matrix by a 3x2 matrix
import numpy as np
a=np.array([[1,2,3],[2,3,4],[3,4,5],[4,5,6],[5,6,7]])
b=np.array([[9,8],[8,7],[6,5]])
print(np.dot(a,b))


[[ 43  37]
 [ 66  57]
 [ 89  77]
 [112  97]
 [135 117]]


In [54]:
#Python program to check two random arrays are equal or not
import numpy as np
a=np.random.normal(1,10,5)
b=np.random.normal(1,10,5)
print(a)
print(b)
if np.array_equal(a,b):
    print('Equal')
else:
    print('Not Equal')

[-1.68689674 -6.36498041  7.96198831  4.07527716 -6.16413412]
[ 3.19487197 -3.54843552  5.213731   -6.45502798 11.28799553]
Not Equal


In [72]:
#program to get n largest values in an array
import numpy as np
a=np.random.uniform(1,5,10)
a=-np.sort(-a)
n=4
print('N largest values are ')
print(a[:n])

N largest values are 
[4.98799481 4.92906378 4.14189973 3.73688138]
