In [34]:
#Q1
import numpy as np
a = np.array([1,2,3,4,5])
print("Original array:")
print(a)
a=a[::-1]
print("reversed array:")
print(a)

Original array:
[1 2 3 4 5]
reversed array:
[5 4 3 2 1]


In [35]:
#Q2
b=np.arange(9).reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
#Q3
c=np.ones((10,10))
c[1:-1,1:-1]=np.zeros((8,8))
print(c)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [36]:
#Q4
d=np.random.random((5,3))

e=np.random.random((3,2))

print(np.dot(d,e))

[[0.75423973 0.98388676]
 [0.86314993 0.78014333]
 [1.01317272 0.85658503]
 [0.58603968 0.76697628]
 [0.31739327 0.27932829]]


In [37]:
#Q6
f=np.random.random((3,3))
g=np.random.random((3,3))
print(np.array_equal(f,g))

False


In [38]:
#Q5
k=np.random.uniform(0,10,10)
print(k)
print(k-k%1)
print(np.ceil(k)-1)
print(np.floor(k))
print(k.astype(int))
print(np.trunc(k))




[8.35827401 2.72649583 7.11661475 8.23330924 2.15867312 8.97648606
 3.88377318 3.54621294 9.41171916 1.17990111]
[8. 2. 7. 8. 2. 8. 3. 3. 9. 1.]
[8. 2. 7. 8. 2. 8. 3. 3. 9. 1.]
[8. 2. 7. 8. 2. 8. 3. 3. 9. 1.]
[8 2 7 8 2 8 3 3 9 1]
[8. 2. 7. 8. 2. 8. 3. 3. 9. 1.]


In [27]:
#Q7&9
w=np.random.uniform(0,5,5)
t=np.random.uniform(0,5)
print(w,t)
min=0
for i in range(0,5,1):
    if(abs(w[i]-t)<abs(w[min]-t)):min=i
print(w[min])

[1.56204438 3.56336734 3.66835618 2.96101569 3.96201493] 3.963671463288997
3.962014925798912


In [33]:
#Q8
#assuming n=4
h=np.random.uniform(0,100,10).astype(int)
print(h)
print(np.sort(h)[-4:])


[70 55 29 63 26  6 16 45 47 39]
[47 55 63 70]


In [32]:
#Q10
i=np.random.random(10)
j=np.argmax(i)
print("INITIAL ARRAY:\n",i)
i[j]=-1
print(i)

INITIAL ARRAY:
 [0.40923285 0.88471774 0.05588803 0.28562566 0.53224849 0.75152313
 0.23335247 0.5821984  0.81043541 0.84755293]
[ 0.40923285 -1.          0.05588803  0.28562566  0.53224849  0.75152313
  0.23335247  0.5821984   0.81043541  0.84755293]


In [31]:
#Q12
k=np.random.random((6,6))
print(k)
n=int(np.random.uniform(0,6))
print(n)
print(np.sort(k[:,n]))
k[:,n]=np.sort(k[:,n])
print(k)

[[0.81292104 0.74332211 0.84890699 0.78968695 0.61149828 0.30024062]
 [0.23573335 0.25640359 0.35591005 0.70803634 0.02195072 0.54339982]
 [0.74993175 0.96181062 0.11091506 0.36301923 0.29484346 0.91077418]
 [0.94574943 0.91364764 0.89874266 0.62641341 0.29044017 0.58301515]
 [0.03230669 0.43152263 0.42727398 0.94440154 0.80509796 0.32027155]
 [0.9922793  0.56066467 0.61534208 0.18402227 0.37882531 0.35941571]]
4
[0.02195072 0.29044017 0.29484346 0.37882531 0.61149828 0.80509796]
[[0.81292104 0.74332211 0.84890699 0.78968695 0.02195072 0.30024062]
 [0.23573335 0.25640359 0.35591005 0.70803634 0.29044017 0.54339982]
 [0.74993175 0.96181062 0.11091506 0.36301923 0.29484346 0.91077418]
 [0.94574943 0.91364764 0.89874266 0.62641341 0.37882531 0.58301515]
 [0.03230669 0.43152263 0.42727398 0.94440154 0.61149828 0.32027155]
 [0.9922793  0.56066467 0.61534208 0.18402227 0.80509796 0.35941571]]


In [30]:
#Q13
o=np.random.random((4,4,4,4))

print(o.sum(axis=(-1,-2)))

[[ 9.07024756  7.26351925  7.32951086  8.24246675]
 [10.37028414  6.15006644  9.02934571  7.13126378]
 [ 9.43606175  8.26129711  6.54823342  7.07356803]
 [ 8.47315347 10.11133724  8.17603859  7.67068009]]


In [29]:

from collections import Counter
#Q14
x=np.random.uniform(0,100,5).astype(int)
print(Counter(x).most_common(1))

[(95, 1)]


In [28]:
#Q11
q=np.random.uniform(0,100,(10,2))

x,y=np.atleast_2d(q[:,0],q[:,1])
print(np.sqrt((x-x.T)**2+(y-y.T)**2))

[[ 0.         56.54636447 48.83444329 30.74708637 41.82812041 15.54517545
  15.41461689 10.92033944 31.75141464 10.36268264]
 [56.54636447  0.         99.82376934 33.16047705 68.69617937 55.37692324
  48.69575286 51.77820619 48.76019874 46.5452317 ]
 [48.83444329 99.82376934  0.         67.31738722 82.30290028 44.48379042
  51.24109075 48.81903716 54.96773277 58.46890524]
 [30.74708637 33.16047705 67.31738722  0.         61.88262834 23.61741543
  17.70421832 21.99003337 16.44833423 24.17081851]
 [41.82812041 68.69617937 82.30290028 61.88262834  0.         56.98603842
  54.49480532 51.26876571 70.54188454 40.13441793]
 [15.54517545 55.37692324 44.48379042 23.61741543 56.98603842  0.
   6.800477    6.27734937 17.69023067 18.90746628]
 [15.41461689 48.69575286 51.24109075 17.70421832 54.49480532  6.800477
   0.          4.73772401 16.55882321 14.68741207]
 [10.92033944 51.77820619 48.81903716 21.99003337 51.26876571  6.27734937
   4.73772401  0.         20.83144004 12.6309777 ]
 [31.75141