In [1]:
import numpy as np

In [2]:
a = np.array([18,9,3])

In [4]:
print (a)

[18  9  3]


In [5]:
a = a[::-1]

In [6]:
print (a) #To print the reversed vector in terms of its coordinates

[ 3  9 18]


In [10]:
b = np.array([[0,8,3],[4,5,2],[1,2,4]]) # A 3x3 matrix

In [9]:
print(b)

[[0 8 3]
 [4 5 2]
 [1 2 4]]


In [13]:
x = np.ones((5,5)) #2D matrix with 1 on the border and 0 inside 


In [14]:
print(x)
x[1:-1,1:-1] = 0 #Subtracting 1 from the inside elements to make it 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [26]:
d = np.array([[1,1,1],[2,2,2],[3,3,3],[4,4,4],[5,5,5]]) #Multiply the matrices


In [18]:
e = np.array([[1,2],[2,3],[1,9]])

In [24]:
v=np.dot(d,e)

In [25]:
print (v)

[[ 4 14]
 [ 8 28]
 [12 42]
 [16 56]
 [20 70]]


In [27]:

x = np.array([3,6,9,12,18])
print("First array:")
print(x)
y = np.array([7,3,9,18,24])
print("Second array:")
print(y)
#to test if the 2 arrays are equal or not
equal = np.allclose(x, y)
print(equal)

First array:
[ 3  6  9 12 18]
Second array:
[ 7  3  9 18 24]
False


In [30]:
i = np.array([1,2,3,4,5,6,7,8,9,10]) #To find a nearest value to the given no 
print("Original array:")
print(i)
s = 5.6
print("Value to compare:")
print(s)
index = (np.abs(i-s)).argmin()
print(i[index])

Original array:
[ 1  2  3  4  5  6  7  8  9 10]
Value to compare:
5.6
6


In [35]:
h=np.array([9,36,24,18,54]) #Print the largest n nos
h=np.sort(h)
u=3
print("after sorting")
print(h)
r=4
while r>=2:
 print(h[r])
 r-=1

after sorting
[ 9 18 24 36 54]
54
36
24


In [38]:
l=np.array([1,4,5,8,54,99]) #Closest value to a given scalar in the array
print(l)
k=7
print("value closest to:")
print(k)
print("is")
index=(np.abs(l-k)).argmin()
print(l[index])

[ 1  4  5  8 54 99]
value closest to:
7
is
8


In [40]:
#The most frequent value can be found using the bincount function.
q = np.array([1,2,3,1,2,1,1,1,3,2,2,1])
counts = np.bincount(q)
print (np.argmax(counts))

1


In [41]:
#the sum of the last 2 axis in a 4D array can be obtained by using sum(axis=(-2,-1))

In [47]:
#sorting the array by the n th column 
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[8 9 1]
 [0 2 2]
 [0 3 5]]
[[0 2 2]
 [0 3 5]
 [8 9 1]]


In [55]:
#random vector of size 15 
x = np.random.random(15)
print("Original array:")
print(x)
x[x.argmax()] = -1
print("Maximum value replaced by -1:")
print(x)


Original array:
[0.72120821 0.478803   0.62580806 0.17417715 0.9632267  0.41945072
 0.06943092 0.83201931 0.10087867 0.34016878 0.20253399 0.42701162
 0.31949659 0.80897792 0.42134388]
Maximum value replaced by -1:
[ 0.72120821  0.478803    0.62580806  0.17417715 -1.          0.41945072
  0.06943092  0.83201931  0.10087867  0.34016878  0.20253399  0.42701162
  0.31949659  0.80897792  0.42134388]
