In [1]:
#importing numpy
import numpy as np

In [10]:
#reverse a vector
a = np.array([1,2,3])
a = a[::-1]
c

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [11]:
#3x3 matrix with values 0 to 8
b = np.arange(0,9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
#2d array with 1 at boundary and 0 inside
c = np.ones((4,4))
c[1:-1, 1:-1]=0
c

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [13]:
#multiply 5x3 matrix by 3x2 matrix
d = np.arange(0,15).reshape(5,3)
e = np.arange(1,7).reshape(3,2)
f = d.dot(e)
f

array([[ 13,  16],
       [ 40,  52],
       [ 67,  88],
       [ 94, 124],
       [121, 160]])

In [135]:
#extract integer part of random array
m = np.random.normal(0,5,10)
print (m - m%1)
print (np.floor(m))
print (np.ceil(m)-1)

'''These two valid only for non-negative numbers'''
n = np.random.uniform(0,5,10)
print (n.astype(int))
print (np.trunc(n))

[ 6.  2. -5. -5.  2. -5. -3. -4.  5. -7.]
[ 6.  2. -5. -5.  2. -5. -3. -4.  5. -7.]
[ 6.  2. -5. -5.  2. -5. -3. -4.  5. -7.]
[3 4 2 2 3 0 1 0 4 3]
[3. 4. 2. 2. 3. 0. 1. 0. 4. 3.]


In [16]:
#check whether two arrays are equal or not
g = np.random.rand(3,3)
h = np.random.rand(3,3)
np.allclose(g,h)

False

In [45]:
#finding nearest value in array from given value
value = 1
i = np.random.rand(3,3)
x = (np.abs(i-value)).argmin()
i.flat[x]


0.9911035048204044

In [47]:
#n greatest values of an array
n=3
arr = np.arange(9).reshape(3,3)
np.random.shuffle(arr)
arrf = arr.flat
ind = np.argsort(arrf)
arrf = arrf[ind]
arrf = arrf[::-1]
arrf[0:n]


array([8, 7, 6])

In [147]:
#How to find the closest value (to a given scalar) in an array?

'''> find absolute difference between the given scalar and each element of the array in the form of an array. 
> find the index of minimum difference. 
> use it to obtain required closest value.'''



'> find absolute difference between the given scalar and each element of the array in the form of an array. \n> find the index of minimum difference. \n> use it to obtain required closest value.'

In [77]:
#replace maximum value by -1

j = np.random.randint(20, size=15)
max = j.max()
while (j.max() == max):
    x = j.argmax()
    j[x]=-1
print(j)

[ 5  7  3 10 16 10 -1  0  5  7 -1  5  0  3 15]


In [150]:
#point to point distances
import math
k = np.random.randint(5, 95, size=200).reshape(100,2)
z = np.zeros((100,100))

for x in range(0,100) :
    for y in range(0,100) :
        z[x,y] = np.trunc(math.sqrt(pow(k[x,0]-k[y,0],2)+pow(k[x,1]-k[y,1],2)))
        
print(z)

[[ 0. 45. 49. ... 58. 70. 58.]
 [45.  0.  8. ... 34. 60. 84.]
 [49.  8.  0. ... 26. 53. 82.]
 ...
 [58. 34. 26. ...  0. 27. 70.]
 [70. 60. 53. ... 27.  0. 56.]
 [58. 84. 82. ... 70. 56.  0.]]


In [145]:
#sort an array by nth column
p = np.random.randint(0,10,(3,3))
x = p[:,2].argsort()
print(p[x])

[[6 9 1]
 [2 6 5]
 [9 5 7]]


In [119]:
#Sum over last two axes of a four dimensional array
A = np.random.randint(0,10,(4,3,4,3))
sum = A.sum(axis=(-1,-2))
print(sum)


[[47 52 51]
 [57 52 45]
 [56 74 49]
 [42 69 39]]


In [124]:
#most frequent value in array
l = np.random.randint(10,15,10)
x = np.bincount(l)
print(np.argmax(x))

[10 14 14 10 13 14 11 12 11 14]
14
