In [10]:
import numpy as np
a = np.arange(9).reshape(3,3)
print(a);

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
a = np.array([1,2,3,4,5,6,7])
a=a[: : -1]

print(a)

[7 6 5 4 3 2 1]


In [17]:
a = np.ones((3,3))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


In [20]:
c=np.random.random(5)
b=np.random.random(5)
print(np.array_equal(c,b))

False


In [35]:
a = np.random.randint(0,100,15)
i = np.argmax(a)
print(a)
a[i]=-1
print(a)
i

[36 51 52 73 32 37 86 93 85  4  4 70 14 27 93]
[36 51 52 73 32 37 86 -1 85  4  4 70 14 27 93]


7

In [37]:
a = np.random.randint(0,10,(3,3))
print(a)
print(a[a[:,1].argsort()])

[[0 7 4]
 [8 9 1]
 [4 2 4]]
[[4 2 4]
 [0 7 4]
 [8 9 1]]


In [39]:
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[9 1 7 5 1 5 8 4 6 8 3 6 2 3 4 8 7 0 4 1 3 5 1 4 3 9 2 3 9 1 7 8 4 9 4 1 8
 1 2 9]
Most frequent value in the above array:
1
