In [2]:
import numpy as np

Imports the numpy library and gives it the reference name 'np' as is convention

In [3]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a)                  # Prints "[5, 2, 3]"
print(a[0])

<class 'numpy.ndarray'>
(3,)
[1 2 3]
1


In [4]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b)

(2, 3)
[[1 2 3]
 [4 5 6]]


Now a few functions to create array.

In [5]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

[[ 0.  0.]
 [ 0.  0.]]


In [6]:

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"


[[ 1.  1.]]


In [7]:

c = np.full((2,2), 7, dtype=np.float64)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"


[[ 7.  7.]
 [ 7.  7.]]


In [8]:

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[ 0.16142539  0.00439001]
 [ 0.1653614   0.94076705]]


Array Math

In [9]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]


In [10]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


In [11]:
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"


[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [12]:
# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"


[1 2 3]
[1 2 3]


In [13]:
nums = list(range(5))     # range is a built-in function that creates a list of integers
print(nums)               # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])          # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])      

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]


In [14]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a)
print(b)
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
77
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
dict = {"country": ["Brazil", "Russia", "India", "China", "South Africa"],
       "capital": ["Brasilia", "Moscow", "New Dehli", "Beijing", "Pretoria"],
       "area": [8.516, 17.10, 3.286, 9.597, 1.221],
       "population": [200.4, 143.5, 1252, 1357, 52.98] }

import pandas as pd
brics = pd.DataFrame(dict)
print(brics)

     area    capital       country  population
0   8.516   Brasilia        Brazil      200.40
1  17.100     Moscow        Russia      143.50
2   3.286  New Dehli         India     1252.00
3   9.597    Beijing         China     1357.00
4   1.221   Pretoria  South Africa       52.98


As you can see with the new brics DataFrame, Pandas has assigned a key for each country as the numerical values 0 through 4. If you would like to have different index values, say, the two letter country code, you can do that easily as well.

In [16]:
# Set the index for brics
brics.index = ["BR", "RU", "IN", "CH", "SA"]

# Print out brics with new index values
print(brics)


      area    capital       country  population
BR   8.516   Brasilia        Brazil      200.40
RU  17.100     Moscow        Russia      143.50
IN   3.286  New Dehli         India     1252.00
CH   9.597    Beijing         China     1357.00
SA   1.221   Pretoria  South Africa       52.98


Another way to create a DataFrame is by importing a csv file using Pandas. Now, the csv cars.csv is stored and can be imported using pd.read_csv:

In [18]:
A = np.random.randint(0,10,(3,4,3,4))
print(A)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[[[7 3 8 1]
   [1 3 8 5]
   [4 8 9 7]]

  [[9 5 4 9]
   [3 4 4 0]
   [4 9 2 8]]

  [[1 2 6 0]
   [5 6 0 3]
   [8 7 0 6]]

  [[2 4 9 5]
   [6 3 1 0]
   [5 0 8 1]]]


 [[[1 3 1 9]
   [8 7 5 4]
   [5 6 2 1]]

  [[2 4 5 5]
   [4 4 0 7]
   [7 4 0 1]]

  [[3 6 9 4]
   [6 0 4 1]
   [7 6 9 9]]

  [[1 7 3 6]
   [2 8 5 0]
   [8 4 1 4]]]


 [[[4 0 3 4]
   [2 9 7 2]
   [4 9 9 0]]

  [[6 9 2 3]
   [0 6 0 0]
   [4 6 7 1]]

  [[1 4 6 6]
   [3 5 4 5]
   [1 9 6 8]]

  [[3 6 2 6]
   [6 1 9 5]
   [3 5 4 6]]]]
[[64 61 44 44]
 [52 43 64 49]
 [53 44 58 56]]


In [21]:
A.shape[:-2]

(3, 4)