In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
print("original array")
print (a)
print("reversed array")
print(a[::-1])

original array
[1 2 3 4 5]
reversed array
[5 4 3 2 1]


In [3]:
a=np.arange(9).reshape([3,3])
print (a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
x = np.random.random((5,3))
print(x)
y = np.random.random((3,2))
print(y)
z = np.dot(x, y)
print(z)

[[ 0.86286956  0.08172448  0.21574745]
 [ 0.621589    0.43538837  0.23665408]
 [ 0.07837583  0.0690936   0.55139956]
 [ 0.15614056  0.93488932  0.02193426]
 [ 0.71655683  0.42077382  0.80103753]]
[[ 0.97954292  0.18351862]
 [ 0.65591067  0.49665179]
 [ 0.01049366  0.35750662]]
[[ 0.9010857   0.27607239]
 [ 0.89693235  0.41491497]
 [ 0.12787791  0.24582787]
 [ 0.76638043  0.5008108 ]
 [ 0.98629402  0.62685581]]


In [5]:
z = np.random.uniform(0,20,10)
print(z)
print (z - z%1)
print (np.floor(z))
print (np.ceil(z)-1)
print (z.astype(int))
print (np.trunc(z))

[ 17.72386081  15.98531867  14.1070962    1.90550251   6.79356433
  10.71310233  11.97527911  17.5678066   15.79206654   9.28300544]
[ 17.  15.  14.   1.   6.  10.  11.  17.  15.   9.]
[ 17.  15.  14.   1.   6.  10.  11.  17.  15.   9.]
[ 17.  15.  14.   1.   6.  10.  11.  17.  15.   9.]
[17 15 14  1  6 10 11 17 15  9]
[ 17.  15.  14.   1.   6.  10.  11.  17.  15.   9.]


In [6]:
x=np.random.rand(5)
print(x)
y=np.random.rand(5)
print(y)
print(np.array_equal(x,y))
print()

[ 0.18412303  0.12810449  0.05608876  0.19900033  0.77642918]
[ 0.78787355  0.71804651  0.79495721  0.55886706  0.57165187]
False



In [7]:
v=0.5
x=np.random.rand(8)
i=(np.abs(x-v)).argmin()
print(x)
print(i)
print(x[i])

[ 0.49735391  0.32108579  0.44779376  0.61138383  0.21603783  0.43020936
  0.61055052  0.65616878]
0
0.497353914927


In [8]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0
print(x)

[[ 1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.]]


In [9]:
x=np.array([2,5,3,7,1,9,4,8,6])
n=3
print (x[np.argsort(x)[-n:]])

[7 8 9]


In [10]:
x=np.random.rand(5)
v=np.random.uniform(0,1)
print(x)
print(v)
i=(np.abs(x-v)).argmin()
print(i)
print(x[i])

[ 0.1397132   0.51420812  0.3312369   0.38000587  0.36089197]
0.18675834291835514
0
0.139713195768


In [11]:
x=np.random.rand(15)
print(x)
x[x.argmax()]=-1
print(x)

[ 0.33580675  0.48959935  0.2405118   0.62470128  0.87450206  0.13695302
  0.54631893  0.63192739  0.51055146  0.26250051  0.8583319   0.80289599
  0.7472918   0.99177666  0.00352956]
[ 0.33580675  0.48959935  0.2405118   0.62470128  0.87450206  0.13695302
  0.54631893  0.63192739  0.51055146  0.26250051  0.8583319   0.80289599
  0.7472918  -1.          0.00352956]


In [12]:
z = np.random.random((10,2))
x,y = np.atleast_2d(z[:,0], z[:,1])
d = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(d)

[[ 0.          0.49531089  0.36056434  0.66378561  0.60559788  0.17034998
   0.04350696  0.20377794  0.52336018  0.55937507]
 [ 0.49531089  0.          0.58792669  0.22324498  0.47473992  0.50081124
   0.45181032  0.61440706  0.04441633  0.3364961 ]
 [ 0.36056434  0.58792669  0.          0.64131216  0.37501809  0.19073359
   0.36028431  0.55485643  0.63090991  0.42005884]
 [ 0.66378561  0.22324498  0.64131216  0.          0.38768943  0.61836517
   0.62199462  0.81294798  0.23627684  0.25394636]
 [ 0.60559788  0.47473992  0.37501809  0.38768943  0.          0.47012277
   0.57908456  0.8051795   0.51550831  0.14240111]
 [ 0.17034998  0.50081124  0.19073359  0.61836517  0.47012277  0.
   0.17054313  0.36921795  0.53855828  0.45619842]
 [ 0.04350696  0.45181032  0.36028431  0.62199462  0.57908456  0.17054313
   0.          0.22609541  0.47991558  0.52553357]
 [ 0.20377794  0.61440706  0.55485643  0.81294798  0.8051795   0.36921795
   0.22609541  0.          0.6309504   0.74700308]
 [ 0.523

In [13]:
x=np.random.random((5,5))
print(x)
n=3
x=x[x[:,n].argsort()]
print(x)

[[ 0.44949163  0.51480366  0.68210849  0.32381175  0.29027147]
 [ 0.79750316  0.55509578  0.87585476  0.68975333  0.94540242]
 [ 0.79215283  0.805366    0.06818053  0.48658882  0.17230748]
 [ 0.07842418  0.30160822  0.48631972  0.01413438  0.20024612]
 [ 0.5830256   0.96152838  0.07257107  0.28794632  0.80367384]]
[[ 0.07842418  0.30160822  0.48631972  0.01413438  0.20024612]
 [ 0.5830256   0.96152838  0.07257107  0.28794632  0.80367384]
 [ 0.44949163  0.51480366  0.68210849  0.32381175  0.29027147]
 [ 0.79215283  0.805366    0.06818053  0.48658882  0.17230748]
 [ 0.79750316  0.55509578  0.87585476  0.68975333  0.94540242]]


In [14]:
x = np.random.randint(0,10,(3,4,3,4))
print(x)
sum = x.sum(axis=(-2,-1))
print(sum)

[[[[8 7 5 2]
   [0 1 4 8]
   [4 3 2 7]]

  [[8 7 1 6]
   [0 1 3 9]
   [2 0 4 2]]

  [[8 4 5 6]
   [3 8 0 3]
   [4 6 5 4]]

  [[0 5 3 8]
   [8 2 4 1]
   [2 5 6 0]]]


 [[[8 5 0 1]
   [2 1 6 1]
   [9 5 7 0]]

  [[7 9 4 2]
   [9 0 3 0]
   [7 7 3 4]]

  [[4 4 9 5]
   [7 4 0 6]
   [5 1 6 3]]

  [[3 1 4 8]
   [0 3 1 0]
   [8 4 9 4]]]


 [[[9 1 2 2]
   [3 5 2 4]
   [1 2 0 9]]

  [[6 1 7 8]
   [1 4 1 0]
   [1 8 4 0]]

  [[5 8 4 3]
   [8 5 2 8]
   [1 2 7 9]]

  [[2 0 5 7]
   [0 3 5 5]
   [0 1 8 2]]]]
[[51 43 56 44]
 [45 55 54 45]
 [40 41 62 38]]


In [15]:
x = np.random.randint(0, 10, 40)
print(x)
print(np.bincount(x).argmax())

[0 1 8 2 9 9 7 0 7 1 5 1 2 7 6 6 8 3 8 0 0 7 3 7 0 9 8 0 1 2 9 8 0 8 8 1 3
 6 8 7]
8
