In [68]:
import numpy as np


In [70]:
#question 1
p = np.array([1,2,3])
p[: : -1]

array([3, 2, 1])

In [82]:
#question 2
q = np.arange(0,9,1)
q.resize(3,3)
q

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [98]:
#question5(i)
m = np.array([[1.1,2.3,3.4], [4.5,5.6,6.7],[7.9,8.8,9.1],[10.2,11.3,12.4],[13.5,14.6,15.7]])
print(np.trunc(m))

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]


In [85]:
#question 5(ii)
m = np.array([[1.1,2.3,3.4], [4.5,5.6,6.7],[7.9,8.8,9.1],[10.2,11.3,12.4],[13.5,14.6,15.7]]) 
m = m-m%1

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]])

In [96]:
#question 5(iii)
m = np.array([[1.1,2.3,3.4], [4.5,5.6,6.7],[7.9,8.8,9.1],[10.2,11.3,12.4],[13.5,14.6,15.7]])
print(np.floor(m))



[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]


In [97]:
#question 5(iv)
m = np.array([[1.1,2.3,3.4], [4.5,5.6,6.7],[7.9,8.8,9.1],[10.2,11.3,12.4],[13.5,14.6,15.7]])
print(np.ceil(m) - 1)


[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]


In [99]:
#question 6
a = np.random.random((2,2))
b = np.random.random((2,2))
np.array_equal(a,b)

False

In [69]:
#question 4
a = np.array([[1,2,3], [4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(a)
b = np.array([[1,2],[3,4],[5,6]])
print(b)

t = np.arange(0,3,1)

m = np.array([[np.sum(a[0,t] * b[t,0]), np.sum(a[0,t] * b[t,1])],[np.sum(a[1,t] * b[t,0]), np.sum(a[1,t] * b[t,1])],[np.sum(a[2,t] * b[t,0]), np.sum(a[2,t] * b[t,1])],[np.sum(a[3,t] * b[t,0]), np.sum(a[3,t] * b[t,1])],[np.sum(a[4,t] * b[t,0]), np.sum(a[4,t] * b[t,1])]])
print(m)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[[1 2]
 [3 4]
 [5 6]]
[[ 22  28]
 [ 49  64]
 [ 76 100]
 [103 136]
 [130 172]]


In [110]:
#question 9
i = 1.0
j = np.random.random((2,2))
print(j)
j = j - i
j.max() + i

[[0.08940007 0.37637719]
 [0.6382021  0.52923088]]


0.6382021019798774

In [120]:
#question 8
k = np.random.random((1,6))
print(k)
k.sort()
print(k)
n = 4
print(k[:1, 2:])  #prints n = 4 greatest values

[[0.63300983 0.71100691 0.90901328 0.07224089 0.47385058 0.42157983]]
[[0.07224089 0.42157983 0.47385058 0.63300983 0.71100691 0.90901328]]
[[0.47385058 0.63300983 0.71100691 0.90901328]]


In [129]:
#question 10
l = np.random.random(15)
print(l)
l[l.argmax()] = -1
print(l)

[0.244275   0.39647265 0.15648258 0.8287738  0.46800873 0.89393455
 0.16401717 0.49686409 0.19427393 0.84822554 0.55143347 0.30261936
 0.8950664  0.27650131 0.89370215]
[ 0.244275    0.39647265  0.15648258  0.8287738   0.46800873  0.89393455
  0.16401717  0.49686409  0.19427393  0.84822554  0.55143347  0.30261936
 -1.          0.27650131  0.89370215]


In [134]:
#question 11
a = np.random.random((3,3))
print(a)
a[a[:,1].argsort()]
print(a)

[[0.1388756  0.34442969 0.15938605]
 [0.07620905 0.63740081 0.75099516]
 [0.37416328 0.48291328 0.0863458 ]]
[[0.1388756  0.34442969 0.15938605]
 [0.07620905 0.63740081 0.75099516]
 [0.37416328 0.48291328 0.0863458 ]]


In [127]:
#question 14
a = np.array([1,2,3,1,2,1,1,1,3,2,2,1])
counts = np.bincount(a)
print(np.argmax(counts))


1
