In [1]:
import numpy as np         #1
a=np.array([4,5,6])
b=a[ : :-1]
print(b)

[6 5 4]


In [2]:
a=np.array([[0,1,2],[3,4,5],[6,7,8]])                  #2
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
a=np.ones((4,4)) # m=4, n=4           #3
i=1
j=1
while(i<3):      # from 1 to m-2 and from 1 to n-2
    j=1
    while(j<3):
        a[i,j]=0
        j=j+1
    i=i+1
print(a)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [17]:
a=np.ones((5,3))                    #4
b=np.ones((3,2))
c=np.dot(a,b)
print(c)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [16]:
a=np.random.uniform(1,5,6)            #5
print(a)
print(a-a%1)
print(np.modf(a))   # seperated integer and fractional parts
print(np.trunc(a))  # { does not
print(np.floor(a))   # {        work for
print(np.ceil(a)-1) # {               negative numbers

[1.30442746 4.3358725  4.6286059  1.75172038 4.01669012 4.46966032]
[1. 4. 4. 1. 4. 4.]
(array([0.30442746, 0.3358725 , 0.6286059 , 0.75172038, 0.01669012,
       0.46966032]), array([1., 4., 4., 1., 4., 4.]))
[1. 4. 4. 1. 4. 4.]
[1. 4. 4. 1. 4. 4.]
[1. 4. 4. 1. 4. 4.]


In [17]:
import numpy as np                #6
a=np.random.random((1,5))
b=np.random.random((1,5))
print(a)
print(b)
print(a==b)

[[0.4862495  0.10634716 0.27152434 0.77812133 0.1368067 ]]
[[0.37387769 0.54492559 0.6860305  0.51011376 0.25874905]]
[[False False False False False]]


In [20]:
a=np.random.uniform(1,5,5)                #7
print(a)
val=4
index=np.absolute(a-val).argmin()
print('Closest value is')
print(a[index])

[4.21354823 2.25720587 4.03616977 3.3125002  2.78309393]
Closest value is
4.036169774798857


In [28]:
a=np.random.uniform(1,10,6)    #8     n=6
print(np.sort(a))
print('Three largest values :')
i=6-3           # for getting the 3 largest values i=n-3
while(i<6):
    print(a[i])
    i+=1

[1.18793807 5.61200249 6.61371436 7.21526568 7.98016259 9.38238911]
Three largest values :
6.613714361093087
7.215265677836472
7.980162589548683


In [ ]:
#9 same as question 7 see above

In [45]:
a=np.random.uniform(1,5,15)                       #10
print(a)
a[np.argmax(a)]=-1     
print(a)

[2.90581225 3.16818599 2.08466231 1.07644788 4.10058442 4.14132719
 4.91758614 3.2124594  3.43152004 1.19876438 4.69859695 4.43899148
 2.1427681  4.46933371 3.26601691]
[ 2.90581225  3.16818599  2.08466231  1.07644788  4.10058442  4.14132719
 -1.          3.2124594   3.43152004  1.19876438  4.69859695  4.43899148
  2.1427681   4.46933371  3.26601691]


In [71]:
a=np.random.uniform(1,100,20).reshape(10,2)          #11
b=a[:,:1]             # first column
c=a[:,1:2]            # second column
print(b)
print(c)
d=np.sqrt((b-b.T)**2 + (c-c.T)**2)   # distance matrix
print(d)

[[17.92022919]
 [52.74872678]
 [89.7495172 ]
 [61.45639444]
 [20.64837416]
 [20.95039866]
 [92.97585522]
 [19.07712503]
 [48.90829042]
 [25.4765599 ]]
[[93.8616928 ]
 [83.47598515]
 [79.95385476]
 [99.26547508]
 [ 2.36813394]
 [66.45520968]
 [67.7803312 ]
 [80.72461857]
 [15.89342509]
 [43.456098  ]]
[[  0.          36.34401145  73.16334175  43.87024673  91.53422358
   27.57348806  79.45806707  13.18791596  83.90060016  50.9688348 ]
 [ 36.34401145   0.          37.16804938  18.03140229  87.22910159
   36.06716607  43.18072968  33.78382427  67.69159013  48.42894231]
 [ 73.16334175  37.16804938   0.          34.25550284 103.89664116
   70.11085601  12.59380533  70.67659508  75.97199782  73.91278163]
 [ 43.87024673  18.03140229  34.25550284   0.         105.13985561
   52.12724057  44.5509898   46.25760301  84.31105285  66.40207123]
 [ 91.53422358  87.22910159 103.89664116 105.13985561   0.
   64.08778741  97.51933176  78.37223684  31.32979999  41.37066797]
 [ 27.57348806  36.06716607  70

In [67]:
a=np.random.uniform(1,10,9).reshape(3,3)             #12
print(a)                                             # soting by the 2nd column
a[a[:,1].argsort()]

[[4.97561598 5.28530323 1.36147465]
 [9.74399387 7.3203344  2.01948697]
 [7.6519167  2.23689318 3.68613492]]


array([[7.6519167 , 2.23689318, 3.68613492],
       [4.97561598, 5.28530323, 1.36147465],
       [9.74399387, 7.3203344 , 2.01948697]])

In [55]:
a=np.random.uniform(1,4,16).reshape(2,2,2,2)          #13
print(a)
print(np.sum(a,axis=(2,3)))

[[[[2.71195799 3.50843019]
   [1.90379887 3.43167563]]

  [[3.7471582  3.10721827]
   [3.4731591  1.81008628]]]


 [[[1.6258269  1.07057781]
   [1.04600861 3.38486197]]

  [[2.34636051 3.78389577]
   [3.8757258  1.29486713]]]]
[[11.55586269 12.13762185]
 [ 7.12727528 11.30084921]]


In [61]:
a=np.array([3,2,3,1,2,1,1,1,3,2,2,1])                    #14
co=np.bincount(a)
print(co)
print(np.argmax(co))

[0 5 4 3]
1
